apiVersion: aperture.itsjool.com/v1
kind: RoleDefinition
metadata:
  name: roles
spec:
  roles:
    Admin:
      description: "Full access to all notes"
    ReadOnly:
      description: "Read-only access to notes"
