package com.itsjool.aperture.mcp;

import com.itsjool.aperture.mcp.McpToolAccessClassifier.ToolAccess;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeSpec;

import javax.lang.model.element.Modifier;
import java.util.Collection;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Generates {@code com.itsjool.aperture.generated.mcp.McpToolRegistry} (plan 016 phase 2): a
 * static map from generated MCP tool name to the {@code McpToolAccess} rule that governs whether
 * {@code tools/list} shows it to a given principal.
 *
 * <p>This is a plain generated-project class, discovered at runtime via reflection — exactly like
 * an {@code McpToolContribution}'s tool class — because generation runs during the build's Maven
 * plugin execution, before the generated project's own JVM exists; there is no live object here to
 * hand a reference to. {@code aperture-simple-mcp}'s {@code McpToolListFilter} reads
 * {@code McpToolRegistry.TOOLS} reflectively.
 *
 * <p><b>This registry is not an authorization boundary.</b> It only shapes what {@code tools/list}
 * shows an agent; {@code tools/call} is still authorized for real by Elide on every invocation,
 * regardless of what this registry says. A bug here can leak a tool <em>name</em>, never data.
 */
public final class McpToolRegistryGenerator {

    private static final String PKG = "com.itsjool.aperture.generated.mcp";
    private static final String REGISTRY_CLASS = "McpToolRegistry";
    private static final String ACCESS_RECORD = "McpToolAccess";

    private static final ClassName STRING_CN = ClassName.get(String.class);
    private static final ClassName SET_CN = ClassName.get(Set.class);
    private static final ClassName LIST_CN = ClassName.get(List.class);
    private static final ClassName MAP_CN = ClassName.get(Map.class);
    private static final ClassName LINKED_MAP_CN = ClassName.get(LinkedHashMap.class);
    private static final ClassName COLLECTIONS_CN = ClassName.get(Collections.class);
    private static final ClassName ACCESS_CN = ClassName.get(PKG, REGISTRY_CLASS, ACCESS_RECORD);

    private McpToolRegistryGenerator() {}

    /** @param toolAccessByName generated tool name (e.g. {@code "list_projects"}) to its access rule */
    public static String generate(Map<String, ToolAccess> toolAccessByName) {
        TypeSpec accessRecord = TypeSpec.recordBuilder(ACCESS_RECORD)
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .addJavadoc("The access rule governing a single generated MCP tool. See the enclosing\n"
                + "class javadoc: this is presentation-only, never an authorization boundary.\n")
            .recordConstructor(MethodSpec.constructorBuilder()
                .addParameter(STRING_CN, "entity")
                .addParameter(STRING_CN, "operation")
                .addParameter(boolean.class, "publicOperation")
                .addParameter(ParameterizedTypeName.get(SET_CN, STRING_CN), "roles")
                .addParameter(ParameterizedTypeName.get(LIST_CN, STRING_CN), "principalOnlyPolicyExpressions")
                .addParameter(boolean.class, "tenantAdminBypass")
                .build())
            .build();

        ParameterizedTypeName mapType = ParameterizedTypeName.get(MAP_CN, STRING_CN, ACCESS_CN);
        FieldSpec toolsField = FieldSpec.builder(mapType, "TOOLS")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
            .build();

        CodeBlock.Builder staticInit = CodeBlock.builder();
        staticInit.addStatement("$T<$T, $T> m = new $T<>()", MAP_CN, STRING_CN, ACCESS_CN, LINKED_MAP_CN);
        for (Map.Entry<String, ToolAccess> entry : toolAccessByName.entrySet()) {
            ToolAccess access = entry.getValue();
            staticInit.addStatement("m.put($S, new $L($S, $S, $L, $L, $L, $L))",
                entry.getKey(), ACCESS_RECORD, access.entity(), access.operation(), access.publicOperation(),
                collectionLiteral(SET_CN, access.roles()),
                collectionLiteral(LIST_CN, access.principalOnlyPolicyExpressions()),
                access.tenantAdminBypass());
        }
        staticInit.addStatement("TOOLS = $T.unmodifiableMap(m)", COLLECTIONS_CN);

        TypeSpec registry = TypeSpec.classBuilder(REGISTRY_CLASS)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addJavadoc("Generated by Aperture (plan 016 phase 2). Maps each MCP tool this application\n"
                + "exposes to the access rule that governs whether {@code tools/list} shows it to a\n"
                + "given principal.\n\n"
                + "<p><b>This is not an authorization boundary.</b> It only shapes what {@code tools/list}\n"
                + "returns; {@code tools/call} is still authorized for real by Elide on every invocation.\n"
                + "A bug in code that consults this registry can leak a tool name, never data, and can\n"
                + "never grant a call that Elide would otherwise reject.\n\n"
                + "<p>Do not edit; this file is regenerated on every build.\n")
            .addType(accessRecord)
            .addField(toolsField)
            .addStaticBlock(staticInit.build())
            .addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build())
            .build();

        return JavaFile.builder(PKG, registry).build().toString();
    }

    private static CodeBlock collectionLiteral(ClassName factory, Collection<String> values) {
        if (values.isEmpty()) {
            return CodeBlock.of("$T.of()", factory);
        }
        StringBuilder format = new StringBuilder("$T.of(");
        Object[] args = new Object[values.size() + 1];
        args[0] = factory;
        int i = 1;
        for (String value : values) {
            if (i > 1) format.append(", ");
            format.append("$S");
            args[i++] = value;
        }
        format.append(")");
        return CodeBlock.of(format.toString(), args);
    }
}
